# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d652161fa50833c47a496e36075b680f686ef6e4a85a492bbfe2814a3d7aa99675eb2d5961792828d416a330e92a3e6281d4e14625f2a27c5c1c0619235be3

test:
  secret_key_base: f3c925b40490c4406d8fbdadac4c5edaa6e796739e269e0426f417cce67a714cdb17e10a7ea4e0dca33a6bd68cdaed27f4d8d206dac3a750b8d2403a08fe0c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
